# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Objects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Objects_Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj_id', models.IntegerField(default=0)),
                ('field_id', models.IntegerField(default=0)),
                ('value', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Objects_Fields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Objects_Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User_Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=200)),
                ('user_id', models.IntegerField(default=0)),
            ],
        ),
    ]
