# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objects_content',
            name='value',
        ),
        migrations.AddField(
            model_name='objects_content',
            name='value_integer',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='objects_content',
            name='value_string',
            field=models.CharField(default='', max_length=400),
        ),
    ]
