# Generated by Django 2.0.7 on 2018-07-09 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot', '0003_auto_20180709_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objects',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_bot.ObjectsTypes'),
        ),
        migrations.AlterField(
            model_name='objectscontent',
            name='field_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_bot.ObjectsFields'),
        ),
        migrations.AlterField(
            model_name='objectscontent',
            name='obj_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_bot.Objects'),
        ),
        migrations.AlterField(
            model_name='objectsfields',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_bot.ObjectsTypes'),
        ),
    ]
